# Generated by Django 2.2 on 2020-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PadreFamilia',
            fields=[
                ('dpi', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='DPI')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'PadreFamilia',
                'verbose_name_plural': 'PadreFamilias',
                'db_table': 'PadreFamilia',
            },
        ),
    ]
