# Generated by Django 2.2 on 2020-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padrefamilia',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='padrefamilia',
            name='fecha_nac',
            field=models.DateField(blank=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
