# Generated by Django 2.2 on 2020-05-19 06:02

from django.db import migrations, models
import django.db.models.deletion
import escuela.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo', models.CharField(default=escuela.models.get_rand_string, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento', verbose_name='Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'Escuela',
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuela.Escuela', verbose_name='Escuela')),
            ],
            options={
                'verbose_name': 'Comite',
                'verbose_name_plural': 'Comites',
                'db_table': 'Comite',
            },
        ),
    ]
