# Generated by Django 2.2 on 2020-05-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Comite', verbose_name='Comite')),
            ],
            options={
                'verbose_name': 'Planificacion',
                'verbose_name_plural': 'Planificaciones',
                'db_table': 'Planificacion',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_prog', models.DateField(verbose_name='Fecha Programada')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo')),
                ('autorizado', models.BooleanField()),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('plainficacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Planificacion', verbose_name='Comite')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividads',
                'db_table': 'Actividad',
            },
        ),
    ]
