# Generated by Django 2.2 on 2020-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='ciclo',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ciclo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together={('comite', 'ciclo')},
        ),
    ]
