# Generated by Django 2.2 on 2020-05-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_auto_20200519_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='autorizado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
