# Generated by Django 2.2 on 2020-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_auto_20200520_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planificacion',
            options={'ordering': ['-ciclo'], 'verbose_name': 'Planificacion', 'verbose_name_plural': 'Planificaciones'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Estado'),
        ),
    ]
