# Generated by Django 2.2 on 2020-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_auto_20200520_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Deportiva', 'Deportiva'), ('Cultural', 'Cultural'), ('Social', 'Social'), ('Artistica', 'Artistica'), ('Academica', 'Academica')], default=1, max_length=25, verbose_name='Tipo de Actividad'),
            preserve_default=False,
        ),
    ]
