# Generated by Django 2.2 on 2020-05-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_pagoactividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoactividad',
            old_name='costo',
            new_name='valor',
        ),
    ]
