# Generated by Django 2.2 on 2020-05-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_auto_20200521_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoactividad',
            name='factura',
        ),
        migrations.AddField(
            model_name='pagoactividad',
            name='uploads/',
            field=models.FileField(default=1, upload_to='', verbose_name='Comprobante'),
            preserve_default=False,
        ),
    ]
