# Generated by Django 2.2 on 2020-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_auto_20200522_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoactividad',
            name='uploads/',
        ),
        migrations.AddField(
            model_name='pagoactividad',
            name='factura',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
