# Generated by Django 2.2 on 2020-05-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_auto_20200522_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoactividad',
            name='factura',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
