# Generated by Django 2.2 on 2020-05-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
        ('padre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('montoInicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Comite', verbose_name='Comite')),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondos',
                'db_table': 'Fondo',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFondo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipoMovimiento', models.BooleanField(verbose_name='Tipo de Movimiento')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('ciclo', models.PositiveSmallIntegerField(verbose_name='Ciclo')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comite.Fondo', verbose_name='Fondo')),
            ],
            options={
                'verbose_name': 'MovimientoFondo',
                'verbose_name_plural': 'MovimientosFondo',
                'db_table': 'MovimientosFondo',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('1', 'Presidente'), ('2', 'Vice Presidente'), ('3', 'Secretario'), ('4', 'Tesorero'), ('5', 'Vocal')], max_length=1, verbose_name='Puesto')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.Comite', verbose_name='Comite')),
                ('padre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='padre.PadreFamilia', verbose_name='Padre de Familia')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['puesto'],
                'unique_together': {('puesto', 'comite')},
            },
        ),
    ]
