# Generated by Django 2.2 on 2020-05-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0002_auto_20200519_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='padre.PadreFamilia', verbose_name='Padre de Familia'),
        ),
    ]
