# Generated by Django 2.2 on 2020-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('comite', '0006_auto_20200519_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='ciclo',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ciclo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fondo',
            name='montoInicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Inicial'),
        ),
        migrations.AlterUniqueTogether(
            name='fondo',
            unique_together={('ciclo', 'comite')},
        ),
    ]
