# Generated by Django 2.2 on 2020-05-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0008_auto_20200521_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fondo',
            options={'ordering': ['-ciclo'], 'verbose_name': 'Fondo', 'verbose_name_plural': 'Fondos'},
        ),
    ]
