# Generated by Django 2.2 on 2020-05-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0009_auto_20200521_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientofondo',
            options={'ordering': ['tipoMovimiento'], 'verbose_name': 'MovimientoFondo', 'verbose_name_plural': 'MovimientosFondo'},
        ),
    ]
