# Generated by Django 2.2 on 2020-05-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0010_auto_20200522_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientofondo',
            options={'ordering': ['-tipoMovimiento'], 'verbose_name': 'MovimientoFondo', 'verbose_name_plural': 'MovimientosFondo'},
        ),
    ]
